spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379