spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
app:
  redis:
    enable: true
    host: localhost
    port: 6379

  cache:
    type: redis
